// Local fallback content, shown whenever the Portfolio.Api endpoint can't be
// reached (e.g. the backend isn't running in dev). Keeps the site rendering
// with real content instead of an empty/broken page, and is fully replaced
// the moment the API responds.
import type { Education, Experience, Profile, Project, SkillCategories } from "@/types/api";

export const fallbackProfile: Profile = {
  name: "Mohamed Hanifa",
  title: "Full Stack .NET Developer",
  tagline: "Open for Senior .NET & AI Engineering Roles",
  summary:
    "Full Stack Software Engineer with 6 years of experience building enterprise-grade applications using .NET, Web Rest Full API, GraphQL, and microservices. Skilled in SQL Server optimization, EF Core and Dapper, with 3 years of experience in Angular and React.js for modern, responsive UI development. Experienced in authentication/authorization (JWT, Basic, Azure AD), scalable microservice architecture, and secure FinTech solutions. Strong collaborator in Agile environments, leveraging Git workflows, TDD, UML, and CQRS.",
  yearsExperience: 6,
  availability: "Available",
  location: "Chennai",
  email: "imdhanifa@outlook.com",
  phone: "+91 9003894244",
  github: "https://github.com/imdhanifa",
  linkedin: "https://www.linkedin.com/in/imdhanifa",
  website: "https://imdhanifa.info",
  resumeUrl: "/api/resume/pdf",
  stats: [
    { label: "Years Exp.", value: "6+" },
    { label: "Enterprise Apps", value: "8+" },
    { label: "Tech Skills", value: "45+" },
  ],
};

export const fallbackSkills: SkillCategories = {
  languages: ["C#", "TypeScript", "JavaScript", "SQL", "HTML5", "CSS3", "SCSS"],
  frontend: [
    "Angular",
    "React.js",
    "Next.js",
    "RxJS",
    "Redux",
    "Bootstrap",
    "Tailwind CSS",
    "Responsive UI/UX",
    "UI Theming",
    "Light/Dark/Multicolor Themes",
    "Micro Frontends",
    "Module Federation",
  ],
  backend: [
    ".NET",
    "ASP.NET Core",
    "RESTful APIs",
    "GraphQL",
    "gRPC",
    "SignalR",
    "Minimal APIs",
    "Worker",
    "Dependency Injection",
    "Middleware",
    "Background Services",
    "Hosted Services",
    "Kestrel",
    "API Versioning",
  ],
  packages: [
    "Dapper",
    "ADO.NET",
    "Entity Framework Core",
    "MediatR",
    "FluentValidation",
    "AutoMapper",
    "Mapster",
    "Serilog",
    "Polly",
    "MassTransit",
    "StackExchange.Redis",
    "Refit",
    "RabbitMQ",
    "FluentAssertions",
    "xUnit",
    "Moq",
    "NUnit",
  ],
  databases: [
    "SQL Server",
    "MSSQL",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "Vector Databases - Learning",
    "Qdrant -Learning",
  ],
  architecture: [
    "Microservices",
    "Monolithic Architecture",
    "Modular Monolith",
    "MVC",
    "Layered Architecture",
    "Clean Architecture",
    "Vertical Slice Architecture",
    "CQRS",
    "Domain-Driven Design (DDD)",
    "Event-Driven Architecture",
    "Distributed Systems",
    "Micro Frontends",
    "Module Federation",
    "SOLID Principles",
    "Design Patterns",
    "Repository Pattern",
    "Unit of Work Pattern",
    "Saga Pattern",
    "Outbox Pattern",
    "Strangler Fig Pattern",
  ],
  security: [
    "JWT",
    "OAuth 2.0",
    "OpenID Connect",
    "ASP.NET Core Identity",
    "Role-Based Access Control (RBAC)",
    "Policy-Based Authorization",
    "Claims-Based Authorization",
    "Microsoft Entra ID",
    "API Security",
    "CORS",
    "CSRF Protection",
    "XSS Protection",
  ],
  ai: ["AI Integration", "Generative AI", "Model Context Protocol (MCP)"],
  devOps: ["Azure DevOps", "GitHub Actions", "Git", "GitHub", "Bitbucket", "TFS", "CI/CD"],
  hosting: [
    "Self-Hosting",
    "Coolify",
    "Docker",
    "Docker Compose",
    "IIS",
    "Domain & DNS Configuration",
  ],
  development_tools: [
    "Visual Studio",
    "Visual Studio Code",
    "SQL Server Management Studio (SSMS)",
    "Postman",
    "Swagger UI",
    "Scalar",
    "GraphiQL / Playground / Altair /Voyager",
    "Docker Desktop",
    "Jira",
    "Confluence",
    "NuGet",
    "npm",
    "Yarn",
    "pnpm",
    "Vite",
    "Webpack",
    "dotnet CLI",
  ],
};

export const fallbackProjects: Project[] = [
  {
    name: "TA (HRMS)",
    description:
      "HRMS platform built for Synergein Technology LLC, covering Time & Attendance, Employee, Organization, Workflow, and Time Management.",
    technologies: [
      ".NET 10",
      "EF Core",
      "React.js",
      "Azure Blob Storage",
      "Azure SQL Database",
      "Microservices",
      "SAAS",
    ],
    link: "https://www.smartv.ae",
  },
  {
    name: "Deluxe Payment Platform (FinTech)",
    description:
      "Secure payment processing platform for Knila IT Solutions with customizable online donation forms, fixed/variable-price sale item management, PCI-compliant Hosted Payment Forms (HPF), recurring payments, transaction tracking and digital wallet integration.",
    technologies: [".NET 8", "GraphQL", "Dapper", "Angular", "React.js", "TypeScript", "Microservices"],
    link: "https://www.deluxe.com",
  },
  {
    name: "Tripwerkz (Travel Tech Platform)",
    description:
      "Online travel booking platform for Tripwerkz India Pvt Ltd offering hotels, flights, tours, transfers and events, with React.js frontend modules and REST APIs integrating TBO Holidays and Hotelbeds.",
    technologies: [".NET Core 3.1", "EF Core", "ADO.NET", "React.js", "Microservices"],
    link: "https://tripwerkz.com",
  },
  {
    name: "React-TS-Advanced",
    description: "Scalable React + TypeScript application with an advanced folder structure and UI theming.",
    technologies: ["React.js", "TypeScript"],
    link: "https://github.com/imdhanifa",
  },
  {
    name: "Angular MFE Host & Remote",
    description: "Micro Frontend architecture built with Angular Module Federation.",
    technologies: ["Angular", "Module Federation"],
    link: "https://github.com/imdhanifa",
  },
  {
    name: "GraphQL.API",
    description: "GraphQL APIs in .NET Core implementing queries and mutations.",
    technologies: [".NET Core", "GraphQL"],
    link: "https://graphql.mugavai.co/grahql",
  },
  {
    name: "Minimal API (FastEndpoints)",
    description: "Lightweight, high-performance APIs in C# built with FastEndpoints.",
    technologies: ["C#", "Minimal APIs", "FastEndpoints"],
    link: "https://github.com/imdhanifa",
  },
  {
    name: "Shopping Bucket List API",
    description: "GraphQL + .NET Core API implementing CQRS with HotChocolate.",
    technologies: [".NET Core", "GraphQL", "CQRS", "HotChocolate"],
    link: "https://github.com/imdhanifa",
  },
];

export const fallbackExperience: Experience[] = [
  {
    company: "Synergein Technology LLC",
    role: "Software Developer",
    location: "Chennai",
    startDate: "2025-10",
    endDate: null,
    current: true,
    description:
      "Developed the BOS TA HRMS platform using .NET, Web API and microservices with Clean Architecture; implemented RBAC, permission management and secure API workflows; optimized SQL Server stored procedures, functions and TVPs; built secure mobile check-in/check-out APIs with GPS, device and request-signature validation.",
    technologies: [".NET", "Web API", "Microservices", "Clean Architecture", "SQL Server", "RBAC"],
  },
  {
    company: "Knila IT Solutions India Pvt Ltd",
    role: "Software Developer",
    location: "Coimbatore",
    startDate: "2022-12",
    endDate: "2025-09",
    description:
      "Built the Deluxe Payment Platform (FinTech) with secure .NET Core / GraphQL APIs and JWT authentication; architected microservices for scalability; built responsive Angular & React.js dashboards for transaction tracking; optimized SQL queries and stored procedures (30% performance improvement); managed data access with Dapper; mentored junior developers.",
    technologies: [".NET Core", "GraphQL", "JWT", "Angular", "React.js", "Dapper", "SQL Server"],
  },
  {
    company: "Tripwerkz India Pvt Ltd",
    role: "Software Developer",
    location: "Chennai",
    startDate: "2021-01",
    endDate: "2022-11",
    description:
      "Developed and deployed microservices-based applications for a global travel platform; built REST APIs and React.js frontend modules for bookings, payments and third-party integrations (TBO Holidays, Hotelbeds); improved performance and maintainability with EF Core and modular architecture; collaborated cross-functionally in Agile teams.",
    technologies: ["Microservices", "REST APIs", "React.js", "EF Core", ".NET Core"],
  },
];

export const fallbackEducation: Education[] = [
  {
    institution: "Mohamed Sathak Polytechnic College",
    degree: "Diploma in Computer Engineering (DCE)",
    startDate: "2016",
    endDate: "2019",
  },
];
